apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus-grafana
  namespace: monitoring
spec:
  gateways:
    - istio-ingress/waffle-ingressgateway
    - mesh
  hosts:
    - grafana.wafflestudio.com
  http:
    - route:
        - destination:
            host: prometheus-grafana.monitoring.svc.cluster.local
            port:
              number: 80
